"""Brief summarization — template MVP; LLM hook for production."""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime

from app.models.items import RawItem


def summarize_brief(*, deltas: list[RawItem], run_id: str) -> str:
    """Build executive markdown brief from delta items."""
    if not deltas:
        return f"# Sentinel Brief — {run_id}\n\n_No new items since last run._\n"

    grouped: dict[str, list[RawItem]] = defaultdict(list)
    for item in deltas:
        grouped[item.source_label].append(item)

    lines = [
        f"# Sentinel Brief — {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        f"**Run:** `{run_id}` · **New items:** {len(deltas)}",
        "",
        "## Executive summary",
        "",
        _executive_summary(deltas),
        "",
        "## By source",
        "",
    ]
    for label, items in sorted(grouped.items()):
        lines.append(f"### {label}")
        lines.append("")
        for item in items[:8]:
            cite = f"[{item.title}]({item.url})"
            snippet = f" — {item.summary[:120]}..." if item.summary else ""
            paywall = " *(paywalled)*" if item.metadata.get("paywalled") else ""
            lines.append(f"- {cite}{paywall}{snippet}")
        lines.append("")
    lines.append("---")
    lines.append("*Generated by Sentinel Brief — governed autonomy (eval + gateway email).*")
    return "\n".join(lines)


def _executive_summary(deltas: list[RawItem]) -> str:
    sources = sorted({d.source_label for d in deltas})
    top = deltas[:5]
    bullets = [f"- **{d.source_label}:** {d.title}" for d in top]
    return (
        f"Overnight scan across **{len(sources)}** sources surfaced **{len(deltas)}** new items. "
        "Highlights:\n\n" + "\n".join(bullets)
    )
